[package]
name = "l3g5nd/vision"
description = "An easy to use UI library for Roblox Lua."
version = "2.2.0"
license = "Apache-2.0"
authors = ["L3G5ND"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Rodux = "roblox/rodux@3.0.0"
TestEZ = "roblox/testez@0.4.1"